// Generated by psc-bundle 0.8.2.0
var PS = { };
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.Eff

  exports.returnE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  // Generated by psc version 0.8.2.0
  "use strict";
  var $foreign = PS["Prelude"];
  var Functor = function (map) {
      this.map = map;
  };
  var Apply = function (__superclass_Prelude$dotFunctor_0, apply) {
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.apply = apply;
  };
  var Applicative = function (__superclass_Prelude$dotApply_0, pure) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.pure = pure;
  };
  var Bind = function (__superclass_Prelude$dotApply_0, bind) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.bind = bind;
  };
  var Monad = function (__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
      this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
      this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
  };                  
  var pure = function (dict) {
      return dict.pure;
  };
  var $$return = function (dictApplicative) {
      return pure(dictApplicative);
  };
  var map = function (dict) {
      return dict.map;
  };
  var bind = function (dict) {
      return dict.bind;
  };
  var $greater$greater$eq = function (dictBind) {
      return bind(dictBind);
  }; 
  var apply = function (dict) {
      return dict.apply;
  };
  var $less$times$greater = function (dictApply) {
      return apply(dictApply);
  };
  var liftA1 = function (dictApplicative) {
      return function (f) {
          return function (a) {
              return $less$times$greater(dictApplicative["__superclass_Prelude.Apply_0"]())(pure(dictApplicative)(f))(a);
          };
      };
  };
  var ap = function (dictMonad) {
      return function (f) {
          return function (a) {
              return bind(dictMonad["__superclass_Prelude.Bind_1"]())(f)(function (v) {
                  return bind(dictMonad["__superclass_Prelude.Bind_1"]())(a)(function (v1) {
                      return $$return(dictMonad["__superclass_Prelude.Applicative_0"]())(v(v1));
                  });
              });
          };
      };
  };
  exports["Monad"] = Monad;
  exports["Bind"] = Bind;
  exports["Applicative"] = Applicative;
  exports["Apply"] = Apply;
  exports["Functor"] = Functor;
  exports["ap"] = ap;
  exports[">>="] = $greater$greater$eq;
  exports["bind"] = bind;
  exports["liftA1"] = liftA1;
  exports["pure"] = pure;
  exports["apply"] = apply;
  exports["map"] = map;;
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.8.2.0
  "use strict";
  var $foreign = PS["Control.Monad.Eff"];
  var Prelude = PS["Prelude"];     
  var monadEff = new Prelude.Monad(function () {
      return applicativeEff;
  }, function () {
      return bindEff;
  });
  var bindEff = new Prelude.Bind(function () {
      return applyEff;
  }, $foreign.bindE);
  var applyEff = new Prelude.Apply(function () {
      return functorEff;
  }, Prelude.ap(monadEff));
  var applicativeEff = new Prelude.Applicative(function () {
      return applyEff;
  }, $foreign.returnE);
  var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
  exports["functorEff"] = functorEff;
  exports["applyEff"] = applyEff;
  exports["applicativeEff"] = applicativeEff;
  exports["bindEff"] = bindEff;
  exports["monadEff"] = monadEff;;
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  exports.unsafeQuerySelector = function (selector) {
    return function (src) {
      return function () {
        return src.querySelector(selector);
      };
    };
  };

  exports.unsafeSetTextContent = function (value) {
    return function (src) {
      return function () {
        src.textContent = value;
        return {};
      };
    };
  };

  exports.unsafeValue = function (src) {
    return function () {
      return src.value;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Element"] = PS["Data.DOM.Simple.Unsafe.Element"] || {});
(function(exports) {
  // Generated by psc version 0.8.2.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Element"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Unsafe_Utils = PS["Data.DOM.Simple.Unsafe.Utils"];
  exports["unsafeValue"] = $foreign.unsafeValue;
  exports["unsafeSetTextContent"] = $foreign.unsafeSetTextContent;
  exports["unsafeQuerySelector"] = $foreign.unsafeQuerySelector;;
 
})(PS["Data.DOM.Simple.Unsafe.Element"] = PS["Data.DOM.Simple.Unsafe.Element"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Events

  exports.unsafeAddEventListener = function (targ) {
    return function (cb) {
      return function (src) {
        return function () {
          src.addEventListener(targ, function (evt) {
            cb(evt)();
          });
        };
      };
    };
  };

  exports.unsafeEventTarget = function (event) {
    return function () {
      return event.target;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Events"] = PS["Data.DOM.Simple.Unsafe.Events"] || {});
(function(exports) {
  // Generated by psc version 0.8.2.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Events"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  exports["unsafeEventTarget"] = $foreign.unsafeEventTarget;
  exports["unsafeAddEventListener"] = $foreign.unsafeAddEventListener;;
 
})(PS["Data.DOM.Simple.Unsafe.Events"] = PS["Data.DOM.Simple.Unsafe.Events"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Window

  exports.unsafeDocument = function (win) {
    return function () {
      return win.document;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Window"] = PS["Data.DOM.Simple.Unsafe.Window"] || {});
(function(exports) {
  // Generated by psc version 0.8.2.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Window"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Document = PS["Data.DOM.Simple.Document"];
  exports["unsafeDocument"] = $foreign.unsafeDocument;;
 
})(PS["Data.DOM.Simple.Unsafe.Window"] = PS["Data.DOM.Simple.Unsafe.Window"] || {});
(function(exports) {
  /* global exports, window */
  "use strict";

  // module Data.DOM.Simple.Window

  exports.globalWindow = window;
 
})(PS["Data.DOM.Simple.Window"] = PS["Data.DOM.Simple.Window"] || {});
(function(exports) {
  // Generated by psc version 0.8.2.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Window"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Unsafe_Window = PS["Data.DOM.Simple.Unsafe.Window"];
  var Data_DOM_Simple_Document = PS["Data.DOM.Simple.Document"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Array = PS["Data.Array"];
  var Data_String = PS["Data.String"];
  exports["globalWindow"] = $foreign.globalWindow;;
 
})(PS["Data.DOM.Simple.Window"] = PS["Data.DOM.Simple.Window"] || {});
(function(exports) {
  // Generated by psc version 0.8.2.0
  "use strict";
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var DOM = PS["DOM"];
  var Data_DOM_Simple_Unsafe_Element = PS["Data.DOM.Simple.Unsafe.Element"];
  var Data_DOM_Simple_Unsafe_Events = PS["Data.DOM.Simple.Unsafe.Events"];
  var Data_DOM_Simple_Unsafe_Window = PS["Data.DOM.Simple.Unsafe.Window"];
  var Data_DOM_Simple_Window = PS["Data.DOM.Simple.Window"];
  var Prelude = PS["Prelude"];     
  var updateBadge = function (event) {
      return function __do() {
          var v = Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Window.unsafeDocument(Data_DOM_Simple_Window.globalWindow))(Data_DOM_Simple_Unsafe_Element.unsafeQuerySelector("#badgeName"))();
          var v1 = Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Events.unsafeEventTarget(event))(Data_DOM_Simple_Unsafe_Element.unsafeValue)();
          return Data_DOM_Simple_Unsafe_Element.unsafeSetTextContent(v1)(v)();
      };
  };
  var main = function __do() {
      var v = Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Window.unsafeDocument(Data_DOM_Simple_Window.globalWindow))(Data_DOM_Simple_Unsafe_Element.unsafeQuerySelector("#inputName"))();
      return Data_DOM_Simple_Unsafe_Events.unsafeAddEventListener("input")(updateBadge)(v)();
  };
  exports["updateBadge"] = updateBadge;
  exports["main"] = main;;
 
})(PS["Main"] = PS["Main"] || {});

PS["Main"].main();
